name: dr_mudtafa_alrifaie
description: "Dr. Mustafa Al-Rifaie Dental Clinic App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  supabase_flutter: ^2.6.0
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "src/assets/images/app_icon_1783724332742.png"

flutter:
  uses-material-design: true
  assets:
    - src/assets/images/
